exclude: "^docs/|/migrations/"
default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.31.1
    hooks:
      - id: djlint-django
        name: djLint Reformatting for Django
        entry: djlint --profile=django --reformat
        types_or: [html]
        language: python

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.31.1
    hooks:
      - id: djlint-django
        name: djLint Checks for Django
        entry: djlint --profile=django
        types_or: [html]
        language: python

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        types_or: [scss, yaml, markdown, javascript, xml]

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
