exclude: "/migrations/"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.5
    hooks:
      - id: djlint-django
        name: djLint Reformatting for Django
        entry: djlint --profile=django --reformat
        types_or: [html]
        language: python

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.5
    hooks:
      - id: djlint-django
        name: djLint Checks for Django
        entry: djlint --profile=django
        types_or: [html]
        language: python

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, json, xml, markdown, scss, javascript]
