exclude: "/migrations/"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-django
        name: djLint Reformatting for Django
        entry: djlint --profile=django --reformat
        types_or: [html]
        language: python

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-django
        name: djLint Checks for Django
        entry: djlint --profile=django
        types_or: [html]
        language: python

  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v16.24.0
    hooks:
      - id: stylelint
        args: [--fix]
        additional_dependencies:
          - stylelint@16.21.0
          - stylelint-config-standard-scss@15.0.1
          - stylelint-config-clean-order@7.0.0

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, json, xml, markdown, scss, javascript]

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.12.1
    hooks:
      - id: zizmor
