[tool.djlint]
ignore="H021,H023,H030,H031"
profile="django"
indent=2

[tool.ruff]
ignore = ["E501", "G004", "PLR2004", "RUF005", "RUF012"] # long lines, fstrings in logs, magic values, consider not concat, mutable classbits
target-version = "py311"
extend-select = ["W", "B", "Q", "C90", "I", "UP", "YTT", "ASYNC", "S", "BLE", "A", "COM", "C4", "DTZ", "T10", "DJ", "EM", "EXE", "FA",
                 "ISC", "ICN", "G", "INP", "PIE", "T20", "PYI", "PT", "Q", "RSE", "RET", "SLF", "SLOT", "SIM", "TID", "TCH", "INT", "PTH",
                 "FIX", "PGH", "PL", "TRY", "FLY", "PERF", "FURB", "RUF"]
unfixable = ["ERA"]
# N: naming, possibly good
# D: docstrings missing throughout
# ANN: annotations missing throughout
# FBT: not convinced boolean trap worth auto-banning.
# CPY: copyright at top of each file
# FA: future annotations -- could s
# G: logging warnings -- fstrings bad?
# ARG: sometimes you need to accept arguments.
# TD: somewhat finicky details about formatting TODOs
# FIX: flags todos: possible to add -- skipped for now
# ERA: lots of false positives, not a good autofix
# PD, NPY, AIR: ignored, panda / numpy / airflow specific



[tool.ruff.extend-per-file-ignores]
"config/*" = ["PGH004", # vague NOQA
              "FIX002"] # TODO: fix this"
"*" = ["RET505"]  # disagree with if X: return Y else: return Z being wrong
"manage.py" = ["B904"]
"*/tests/*" = ["S101"]
"fabfile.py" = ["S603", "S607", "PLW1510",  # TODO: should probably rework these
               "T201"]  # OK to have prints here
"merge_production_dotenvs_in_dotenv.py" = ["S101"]  # TODO: fix this
"*.*" = ["DTZ001", "DTZ007", "INP001", "PTH123", "PTH110"] # TODO: fix
"judgments/*" = ["FIX002"] # TODOs, should fix
"conftest.py" = ["PT004"] # not even sure what this code is doing.

[tool.ruff.isort]
known-first-party = ["ds-caselaw-editor-ui", "config"]

[tool.ruff.pycodestyle]
