volumes:
  ds_caselaw_editor_ui_local_postgres_data: {}
  ds_caselaw_editor_ui_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: ds_caselaw_editor_ui_local_django
    container_name: ds_caselaw_editor_ui_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.test/.django
      - ./.envs/.test/.postgres
    ports:
      - "3000:3000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: ds_caselaw_editor_ui_production_postgres
    container_name: ds_caselaw_editor_ui_local_postgres
    volumes:
      - ds_caselaw_editor_ui_local_postgres_data:/var/lib/postgresql/data:Z
      - ds_caselaw_editor_ui_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.test/.postgres

  marklogic:
    container_name: marklogic
    image: store/marklogicdb/marklogic-server:10.0-8.1-centos-1.0.0-ea2
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    environment:
      MARKLOGIC_ADMIN_USERNAME: admin
      MARKLOGIC_ADMIN_PASSWORD: admin
      MARKLOGIC_INIT: "true"
    volumes:
      - ./docker/db/data/:/var/opt/MarkLogic/

  docs:
    image: ds_caselaw_editor_ui_local_docs
    container_name: ds_caselaw_editor_ui_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.test/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./ds_caselaw_editor_ui:/app/ds_caselaw_editor_ui:z
    ports:
      - "7000:7000"
    command: /start-docs
