# Generated by Django 5.2.8 on 2025-12-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkReparseRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('documents_in_queue', models.IntegerField()),
                ('target_parser_version', models.TextField()),
                ('documents_selected', models.IntegerField(null=True)),
                ('documents_attempted', models.IntegerField(null=True)),
                ('documents_skipped', models.IntegerField(null=True)),
                ('documents_failed', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Bulk Reparse Run Log',
                'verbose_name_plural': 'Bulk Reparse Run Logs',
            },
        ),
    ]
