# Generated by Django 5.2.8 on 2025-12-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkreparserunlog',
            options={'ordering': ['-start_time'], 'verbose_name': 'Bulk Reparse Run Log', 'verbose_name_plural': 'Bulk Reparse Run Logs'},
        ),
    ]
