# Generated by Django 5.2.8 on 2025-12-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgments', '0002_alter_bulkreparserunlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkreparserunlog',
            name='status',
            field=models.CharField(blank=True, choices=[('STA', 'Started'), ('FAI', 'Failed'), ('FIN', 'Finished')], max_length=3),
        ),
    ]
