# Generated by Django 5.2.8 on 2025-12-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgments', '0003_bulkreparserunlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkreparserunlog',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
