#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

npm run build
python /app/manage.py collectstatic --noinput
cd /app
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app --access-logfile - -w 5 --access_log_format '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" %(L)s "%({x-forwarded-for}i)s"'
