name: E2E Staging Tests

on:
  push:
  schedule:
    - cron: "0 8 * * *"
  workflow_call:
    secrets:
      CYPRESS_USERNAME:
        required: true
      CYPRESS_PASSWORD:
        required: true

jobs:
  qa_e2e_tests_on_staging:
    name: Run Staging E2E Cypress Tests
    uses: ./.github/workflows/e2e_cypress_tests.yml
    with:
      CYPRESS_BASE_URL: "https://editor.staging.caselaw.nationalarchives.gov.uk"
    secrets:
      CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
      CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
