name: E2E Cypress Tests

on:
  workflow_call:
    inputs:
      CYPRESS_BASE_URL:
        required: true
        type: string
    secrets:
      CYPRESS_USERNAME:
        required: true
      CYPRESS_PASSWORD:
        required: true

jobs:
  run-e2e-cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Install Node.js and npm
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: .node-version

      - name: Install Cypress
        run: npm install cypress

      - name: Run Cypress Tests
        run: CYPRESS_BASE_URL=${CYPRESS_BASE_URL} CYPRESS_USERNAME=${{secrets.CYPRESS_USERNAME}} CYPRESS_PASSWORD=${{secrets.CYPRESS_PASSWORD}} npx cypress run --headless

env:
  CYPRESS_BASE_URL: ${{inputs.CYPRESS_BASE_URL}}
