name: E2E Cypress Tests

on:
  workflow_call:
    secrets:
      CYPRESS_USERNAME:
        required: true
      CYPRESS_PASSWORD:
        required: true

jobs:
  run-e2e-cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Cypress
        run: npm install cypress

      - name: Run Cypress Tests
        run: CYPRESS_USERNAME=${{secrets.CYPRESS_USERNAME}} CYPRESS_PASSWORD=${{secrets.CYPRESS_PASSWORD}} npx cypress run --headless
