name: Release latest code for production deploy
permissions: {}
on:
  release:
    types: [published]

jobs:
  pre_release-qa_e2e_tests_on_staging:
    uses: ./.github/workflows/e2e_staging_tests.yml
    secrets:
      CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
      CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

  release:
    needs: pre_release-qa_e2e_tests_on_staging
    name: Run local action
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: true
      - name: Run latest-tag
        uses: EndBug/latest-tag@7589411ebda7bc8f98deb2dbc37e3dc45828f7d0 # v1.6.2
        with:
          ref: production
          force-branch: true
