name: Release latest code for production deploy
permissions: {}
on:
  release:
    types: [published]

jobs:
  pre_release-qa_e2e_tests_on_staging:
    uses: ./.github/workflows/e2e_staging_tests.yml
    secrets:
      CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
      CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

  release:
    needs: pre_release-qa_e2e_tests_on_staging
    name: Run local action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          ref: production
          force-branch: true
