name: Source safety
permissions: {}
on:
  pull_request:
  push:
jobs:
  secrets:
    name: Check for secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false
      - uses: nationalarchives/tdr-github-actions/.github/actions/run-git-secrets@305d1b677f31b77f35cd4679ebd469857de9e967
